<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="10" total="11" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-04T11:20:17 IST" name="Default suite" finished-at="2023-04-04T11:20:18 IST" duration-ms="1202">
    <groups>
      <group name="NotLoggedIn">
        <method signature="CheckoutPageTest.TitleVerification(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.dotKonnekt.tests.CheckoutPageTest@62230c58]" name="TitleVerification" class="com.dotKonnekt.tests.CheckoutPageTest"/>
      </group> <!-- NotLoggedIn -->
    </groups>
    <test started-at="2023-04-04T11:20:17 IST" name="Default test" finished-at="2023-04-04T11:20:18 IST" duration-ms="1202">
      <class name="com.dotKonnekt.tests.CheckoutPageTest">
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.dotKonnekt.tests.CheckoutPageTest@62230c58]" started-at="2023-04-04T11:20:16 IST" name="loadConfig" finished-at="2023-04-04T11:20:17 IST" duration-ms="541" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method signature="TitleVerification(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.dotKonnekt.tests.CheckoutPageTest@62230c58]" started-at="2023-04-04T11:20:18 IST" name="TitleVerification" data-provider="CheckoutPage" finished-at="2023-04-04T11:20:18 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException: -1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException: -1
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
at org.testng.internal.Parameters.handleParameters(Parameters.java:791)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:917)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NegativeArraySizeException: -1
at com.dotKonnekt.dataProviders.DataProviders.CheckoutDetails(DataProviders.java:282)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TitleVerification -->
        <test-method is-config="true" signature="flush()[pri:0, instance:com.dotKonnekt.tests.CheckoutPageTest@62230c58]" started-at="2023-04-04T11:20:18 IST" name="flush" finished-at="2023-04-04T11:20:18 IST" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush -->
      </class> <!-- com.dotKonnekt.tests.CheckoutPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
