<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GarvitDevice" failures="1" tests="4" name="com.dotKonnektMobile.tests.BlogPageTest" time="46.787" errors="0" timestamp="2023-05-17T11:05:52 IST" skipped="3">
  <testcase classname="com.dotKonnektMobile.tests.BlogPageTest" name="BlogPage_bookMarkIconFunctionalityLoggedIn_dotFashion" time="46.787">
    <failure message="Count not increased expected [1] but found [2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Count not increased expected [1] but found [2]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at com.dotKonnektMobile.pages.RecipePageFinal.BookMarkIconfunctionality(RecipePageFinal.java:228)
at com.dotKonnektMobile.tests.BlogPageTest.BlogPage_bookMarkIconFunctionalityLoggedIn_dotFashion(BlogPageTest.java:332)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- BlogPage_bookMarkIconFunctionalityLoggedIn_dotFashion -->
  <system-out/>
  <testcase classname="com.dotKonnektMobile.tests.BlogPageTest" name="BlogPage_AddCommentinCommentSeection_dotFashion">
    <skipped/>
  </testcase> <!-- BlogPage_AddCommentinCommentSeection_dotFashion -->
  <system-out/>
  <testcase classname="com.dotKonnektMobile.tests.BlogPageTest" name="BlogPage_reportAbuseFunctionality_dotFashion">
    <skipped/>
  </testcase> <!-- BlogPage_reportAbuseFunctionality_dotFashion -->
  <system-out/>
  <testcase classname="com.dotKonnektMobile.tests.BlogPageTest" name="BlogPage_likeIconFunctionality_dotFashion">
    <skipped/>
  </testcase> <!-- BlogPage_likeIconFunctionality_dotFashion -->
  <system-out/>
</testsuite> <!-- com.dotKonnektMobile.tests.BlogPageTest -->
